### ISSUE TITLE
엄랭의 인코딩 방식이 어떻게 되나요?

### ISSUE THREAD

**Issue by StrayDog041204** [rycont/umjunsik-lang#2]
엄랭으로부터 영감을 받아서 엄랭을 파이썬 언어로 변환해 주는 프로그램을 만들려고 하는데, 엄랭 파일(.umm 확장자)의 인코딩 방식이 어떻게 되나요?

**Comment by rycont** [comment]
엄랭디노는 UTF-8을 기준으로 제작되었지만, 딱히 언어단에서 인코딩 방식을 규정하고 있지는 않습니다!
