### ISSUE TITLE
엄씨가 제대로 동작하지 않습니다.

### ISSUE THREAD

**Issue by adp-study** [rycont/umjunsik-lang#23]
리눅스 우분투에서 git으로 받고 컴파일하면 example 파일을 실행하여도 어떻게 이 코드가 엄랭이냐ㅋㅋ 만 출력됩니다.

엄랭을 https://www.ryugod.com 에 추가하려고 하니 확인해주세요~

원하지 않으면 온라인 IDE에 추가하지 않겠습니다 ^^

**Comment by adp-study** [comment]
parse.c 에서 "이 사람이름이냐" 비교를 "이 사람이름이냐ㅋㅋ"로 바꾸어 컴파일하였습니다.

**Comment by adp-study** [comment]
온라인 개발환경이 적용되었습니다. 구문강조기능도 완벽히 됩니다!
http://www.ryugod.com/pages/개발환경/umm
테스트해보면 99베어스 소스 출력 결과가 정상적이지 않습니다.

**Comment by adp-study** [comment]
주석처리가 불가능하여 소스에 출처를 기입할 수 없습니다. 주석 기능이 필요합니다.

**Comment by rycont** [comment]
@adp-study 프로젝트에 많은 관심을 가져주셔서 고맙습니다👍 말씀주신부분은 향후 업데이트에 포함하겠습니다!

**Comment by rycont** [comment]
@all-contributors please add @adp-study for infra, bug
