### ISSUE TITLE
초안/미구현 : 변수연산 예제 문제

### ISSUE THREAD

**Issue by Sayori1576** [rycont/umjunsik-lang#47]
우선순위를 적용하지 않는다고 설명에 써져 있으나 예제에는 우선순위가 적용되어 있습니다

**Comment by rycont** [comment]
아.. 그렇네요
사칙연산 우선순위를 적용하는게 좋을까요? @Sayori1576

**Comment by Sayori1576** [comment]
저는 적용한다면 구현이 어려워질 것 같다고 생각합니다...

**Comment by Sayori1576** [comment]
기존 소스와 호환이 되지 않을 수도 있고요.

**Comment by rycont** [comment]
다른 구현체의 경우에는 잘 모르겠지만, 레퍼런스 디노 구현체는 띄어쓰기를 기준으로 표현식을 분할해서 값을 평가하고 있었어서.. 사실 구현이 가장 쉬운편은 더하기와 빼기의 우선순위를 곱하기/나누기보다 더 높게 책정하는겁니다!!
이 방안은 어떨까요!? 훨씬 난해해지겠네요

**Comment by Sayori1576** [comment]
@rycont 
![r](https://user-images.githubusercontent.com/93511899/152950716-d3abd5ee-c4f6-4058-9fb7-093a18910bef.PNG)
또한 변수 지정과 사용칸의 설명이 모순되는 문제점을 발견했습니다. 혹시 어느 쪽이 맞나요?

**Comment by rycont** [comment]
@Sayori1576 어떤 부분이 모순인지 더 자세히 설명해 주실 수 있을까요?

**Comment by Sayori1576** [comment]
@rycont 위에는 어엄.이 2번째 변수에 대입이라고 써져 있지만 밑에는 어어가 2번째 변수라고 쓰여져 있어요.

**Comment by rycont** [comment]
명세에 나온대로 연음 음소의 갯수를 따르기 때문에 "어엄"이 2번째 변수에 대입하는 표현으로, "어어"가 2번째 변수의 값을 가져오는 표현으로 해석되는것이 의도에 맞습니다

**Comment by Sayori1576** [comment]
아 그렇군요, 죄송합니다.

**Comment by Sayori1576** [comment]
@rycont 
[Umpp-master.zip](https://github.com/rycont/umjunsik-lang/files/8029736/Umpp-master.zip)
제가 만들고 있는 [C++ 구현체](https://github.com/Sayori1576/Umpp)에 변수연산 기능을 구현해 봤습니다. 취지에 잘 맞는지 확인해 주세요.
