### ISSUE TITLE
모든 구현체의 작동방식을 C구현체 작동방식으로 통일시켜주세요.

### ISSUE THREAD

**Issue by pizzaroot** [rycont/umjunsik-lang#48]
```
어떻게
식식?식?!
이 사람이름이냐ㅋㅋ
```
와 같은 입력끼리의 덧셈 연산은 C구현체에서는 가능하지만 Web구현체에서는 올바르게 동작하지 않습니다.

```
어떻게
엄
동탄어?화이팅!
준...
이 사람이름이냐ㅋㅋ
```
처럼 화이팅!이 C구현체에서는 작동하여 정상종료 되지만, Web구현체에서는 올바르게 동작하지 않습니다.

정수 연산도 C의 int범위를 넘어갔을때 C구현체와 동일한 방식으로 다른 구현체도 작동되게 통일시켜주세요.

**Comment by Pizzaroot** [comment]
웹엄을 수정해서 호스팅했습니다
https://umm.arena.openmath.co.kr/

**Comment by finalchild** [comment]
C의 int 범위를 넘어섰을 때 C 구현체는 UB인데 정확히 어떤 방식을 말씀하시는지 설명이 필요합니다.
