### ISSUE TITLE
웹-엄 구현체 관련

### ISSUE THREAD

**Issue by kms0219kms** [rycont/umjunsik-lang#73]
안녕하십니까, 저는 디스코드에서 웹개발자로 활동중인 SSKATE 입니다.

웹-엄이 현재 접속되지 않는다는 문구를 보고, 제가 한번 호스팅 할 수 있겠다고 생각하여, 아래 URL로 배포하였습니다.
Cloudflare CDN을 이용하므로 연결도 안정적일 것이라고 생각합니다.

https://umjunsik-lang.sskate.me/

연결이 불능 등의 문제가 발생한다면, 저에게 바로 메일 주신다면 확인해 드릴 수 있습니다.
[minsu_kim@bishanoi.net](mailto:minsu_kim@bishanoi.net) or [kms0219kms@kakao.com](mailto:kms0219kms@kakao.com)

**Comment by kms0219kms** [comment]
@rycont

**Comment by rycont** [comment]
귀중한 시간 내서 작업해주셔서 고맙습니다. 리드미에 걸려있는 웹엄 주소를 위 링크로 대체하겠습니다😍
